# Домашнее задание #1

Для начала вам понадобится импортировать модуль `numpy` как `np`

In [2]:
import numpy as np

## Задача №1

Считайте (через `input`) 2 числа: <br>
`n` - размер `Numpy` вектора; <br>
`x` - координата элемента вектора, который должен быть равен `1`. Остальные должны быть равны `0`. <br>
Создайте вектор размера `n`, в котором все элементы равны `0`, кроме элемента с номером `x` - он равен `1`.


In [5]:
n = int(input())
x = int(input())
v = np.linspace(0,0,n)
v[x]=1
print(v)

5
2
[0. 0. 1. 0. 0.]


## Задача №2

Считайте 3 числа: `n, m, s`. Создайте `Numpy` вектор, состоящий из чисел от `n` до `m` с шагом `s`.

In [11]:
n = int(input())
m = int(input())
s = int(input())
a = np.arange(n,m,s)
print(a)

1
10
2
[1 3 5 7 9]


## Задача №3

Создайте матрицу `3х3` со значениями от `0` до `8`. Значения нужно сгенерировать.

In [12]:
b = np.linspace(0, 8, 9)
b.shape = 3,3
print(b)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


## Задача №4

1. Создайте матрицу `4х4` со случайными значениями.
2. Найдите максимальное значение первой строки, минимальное - второй, среднее - третьей, сумму - четвертой.

In [15]:
c = np.random.random(16)
c.shape = 4,4
print(c[0].max())
print(c[1].min())
print(c[2].mean())
print(c[3].sum())

0.7307755001276426
0.6659686877650131
0.5693468508896969
1.6879284746452754


## Задача №5

Создайте диагональную матрицу `5х5`, все ненулевые элементы равны 5.

In [21]:
d = np.eye(5)
d = d*5
print(d)


[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


## Задача №6

Создайте `Numpy` массив случайных чисел размерности `6х6х6` и найдите максимальное значение среди всех элементов.

In [19]:
e = np.random.random(6**3)
e.shape = 6,6,6
print(e.max())

0.9918474630372078


## Задача №7

Напишите функцию, которая принимает на вход 2 `Numpy` матрицы, проверяет, можно ли их перемножить, и если можно - то перемножает и возвращает транспонированную результирующую матрицу.

In [24]:
def multiply(a,b):
    if a.shape[1] == b.shape[0]:
        return (a@b).T
    else:
        print("Матрицы невозвомжно перемножить")

## Задача №8

Эту задачу можете как запрограммировать, так и решить на листочке.

Но проще, конечно, **запрограммировать**.

Здесь вам придется заглянуть в ноутбук ["Функция одной переменной/Производная функции многих переменных"](./Derivative.ipynb) и убедиться, что вы поняли, как дифференцировать функцию многих переменных, а также в ноутбук ["Оптимизация функции одной и многих переменных"](./Optimization.ipynb) и убедиться, что вы поняли, как работает градиентный спуск. Если все-таки не поняли - пишите в [чат](https://t.me/joinchat/01_ttlSQj3hjZTg6), тегайте меня, `@leonidt`, пришлю вам что-нибудь в помощь.

Дана функция:

$$ f(x_1, x_2) = x_1^2 + 2x_2^2 + e^{x_1+x_2} $$

Найдите минимум данной функции, завершив вычисления при погрешности $$\varepsilon = 0.5 $$, выбрав в качестве начального приблежения точку `(0, 0)` и коэффициент шага $$ H=0.1. $$